version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: coffeedb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on: [db]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coffeedb
      SPRING_DATASOURCE_USERNAME: pguser
      SPRING_DATASOURCE_PASSWORD: pgpass
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "4200:80"

volumes:
  db-data:
